{
    "type": "relationship",
    "id": "relationship--3cd8146a-8d50-4a36-8d8c-3c80e7b63105",
    "created_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
    "created": "2021-03-01T21:55:30.036Z",
    "modified": "2021-03-01T21:55:30.036Z",
    "relationship_type": "uses",
    "description": "[Pysa](https://attack.mitre.org/software/S0583) has used Python scripts to deploy ransomware.(Citation: CERT-FR PYSA April 2020)",
    "source_ref": "malware--a19c1197-9414-46e3-986f-0f609ff4a46b",
    "target_ref": "attack-pattern--cc3502b5-30cc-4473-ad48-42d51a6ef6d1",
    "external_references": [
        {
            "source_name": "CERT-FR PYSA April 2020",
            "description": "CERT-FR. (2020, April 1). ATTACKS INVOLVING THE MESPINOZA/PYSA RANSOMWARE. Retrieved March 1, 2021.",
            "url": "https://www.cert.ssi.gouv.fr/uploads/CERTFR-2020-CTI-003.pdf"
        }
    ],
    "object_marking_refs": [
        "marking-definition--fa42a846-8d90-4e51-bc29-71d5b4802168"
    ],
    "x_mitre_modified_by_ref": "identity--c78cb6e5-0c4b-4611-8297-d1b8b55e40b5",
    "x_mitre_version": "1.0"
}